### PR TITLE
Bootstrap 7.0.5

### PR DESCRIPTION
**Pull request by gilbertsoft**
Fixes issue #4. Looks good with version 7.0.5: http://aimeos.demo.gilbertsoft.net

### CODE REVIEW

**Comment by aimeos** [comment]
Thanks, we've didn't noticed that bootstrap_package was limited to 7.0.x

**Comment by gilbertsoft** [comment]
Is a strange behaviour, older versions are compatible, the newest not!? Currently I'm fighting with realurl, does not support PHP 7.1, 7.0 only!? And the second problem is probably an issue with aimeos dist, but later more...

Have you seen, Aimeos is the only dist for T3 8.6 (except the intro)! Hope this will push Aimeos next months... :-D

**Comment by gilbertsoft** [comment]
Please update https://aimeos.org/docs/TYPO3/Install_Aimeos/Prerequisites, does not include T3 8!

**Comment by gilbertsoft** [comment]
Consider delete T3 4 versions from https://aimeos.org/docs/TYPO3/Install_Aimeos/Install_and_configure

**Comment by aimeos** [comment]
Documentation is updated. Thanks for the hint!
Would you like to get your own Wiki account so you can change things on your own?

**Comment by gilbertsoft** [comment]
Why not, could be easier....

**Pull request merged**
